### ISSUE TITLE
Can not get the plugin due to the bellow Error.

### ISSUE THREAD

**Issue by richard457** [the-meedu-app/flutter-facebook-auth#14]
Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons. [extra]: , null)

**Comment by richard457** [comment]
seems to be a token issue but how to fix it?

**Comment by the-meedu-app** [comment]
> seems to be a token issue but how to fix it?

I that case if you are using the the facebook access token to make other actions not only for login you must force re-login to the user

**Comment by the-meedu-app** [comment]
> > seems to be a token issue but how to fix it?
> 
> I that case if you are using the the facebook access token to make other actions not only for login you must force re-login to the user

You can use `final accessToken = await FacebookAuth.instance.isLogged;` to check if the user is logged if this returns null you can force re-login

**Comment by the-meedu-app** [comment]
> seems to be a token issue but how to fix it?



> > > seems to be a token issue but how to fix it?
> > 
> > 
> > I that case if you are using the the facebook access token to make other actions not only for login you must force re-login to the user
> 
> You can use `final accessToken = await FacebookAuth.instance.isLogged;` to check if the user is logged if this returns null you can force re-login

also you can update the plugin version
