### ISSUE TITLE
[iOS] Returns error 403 if user is not signed into facebook on safari and has facebook app installed

### ISSUE THREAD

**Issue by mrgnhnt96** [the-meedu-app/flutter-facebook-auth#17]
If I am signed into facebook on safari (regardless if I have the facebook app) it allows me to login from the browser bottom sheet that is opened within the app. 

However, if I am not signed into facebook on safari AND if I have the facebook app installed, it will ask if I want to login via the facebook app, which you have to agree to to sign in as it doesn't let you sign in from the bottom sheet. 

After being redirected to the facebook app, allowing to sign in, I get redirected back to the app and get an error 403 and no token to sign in/get creds.

**Comment by the-meedu-app** [comment]
> If I am signed into facebook on safari (regardless if I have the facebook app) it allows me to login from the browser bottom sheet that is opened within the app.
> 
> However, if I am not signed into facebook on safari AND if I have the facebook app installed, it will ask if I want to login via the facebook app, which you have to agree to to sign in as it doesn't let you sign in from the bottom sheet.
> 
> After being redirected to the facebook app, allowing to sign in, I get redirected back to the app and get an error 403 and no token to sign in/get creds.

Please provide more information as if you has been configured the AppDelegate.swift

**Comment by mrgnhnt96** [comment]
Here are the contents of my AppDelegate.swift
```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**Comment by the-meedu-app** [comment]
> Here are the contents of my AppDelegate.swift
> 
> ```swift
> import UIKit
> import Flutter
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     GeneratedPluginRegistrant.register(with: self)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> ```

You need add some code in your AppDelegate.swift
https://github.com/the-meedu-app/flutter-facebook-auth#important-1

**Comment by the-meedu-app** [comment]
> > Here are the contents of my AppDelegate.swift
> > ```swift
> > import UIKit
> > import Flutter
> > 
> > @UIApplicationMain
> > @objc class AppDelegate: FlutterAppDelegate {
> >   override func application(
> >     _ application: UIApplication,
> >     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
> >   ) -> Bool {
> >     GeneratedPluginRegistrant.register(with: self)
> >     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
> >   }
> > }
> > ```
> 
> You need add some code in your AppDelegate.swift
> https://github.com/the-meedu-app/flutter-facebook-auth#important-1

> If I am signed into facebook on safari (regardless if I have the facebook app) it allows me to login from the browser bottom sheet that is opened within the app.
> 
> However, if I am not signed into facebook on safari AND if I have the facebook app installed, it will ask if I want to login via the facebook app, which you have to agree to to sign in as it doesn't let you sign in from the bottom sheet.
> 
> After being redirected to the facebook app, allowing to sign in, I get redirected back to the app and get an error 403 and no token to sign in/get creds.



> Here are the contents of my AppDelegate.swift
> 
> ```swift
> import UIKit
> import Flutter
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     GeneratedPluginRegistrant.register(with: self)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> ```

Update to `flutter_facebook_auth: ^0.3.0` to avoid the configuration inside `AppDelegate.swift`
