### ISSUE TITLE
flutter_facebook_auth depends on a too old version of FBSDKCoreKit compared to facebook_app_events

### ISSUE THREAD

**Issue by jgrandchavin** [the-meedu-app/flutter-facebook-auth#20]
Hello,

I have an issue with your lib because FBSDKCoreKit is too old in flutter_facebook_auth compared to facebook_app_events, so my pod install can't be successful.

`[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
      In snapshot (Podfile.lock):
        FBSDKCoreKit (= 5.15.1, ~> 5.0)

      In Podfile:
        facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
          FBSDKCoreKit (~> 7.1.0)

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `FBSDKCoreKit` inside your development pod `facebook_app_events`.
       You should run `pod update FBSDKCoreKit` to apply changes you've made.`

Thanks !

**Comment by the-meedu-app** [comment]
> Hello,
> 
> I have an issue with your lib because FBSDKCoreKit is too old in flutter_facebook_auth compared to facebook_app_events, so my pod install can't be successful.
> 
> `[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
> In snapshot (Podfile.lock):
> FBSDKCoreKit (= 5.15.1, ~> 5.0)
> 
> ```
>   In Podfile:
>     facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
>       FBSDKCoreKit (~> 7.1.0)
> 
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * changed the constraints of dependency `FBSDKCoreKit` inside your development pod `facebook_app_events`.
>    You should run `pod update FBSDKCoreKit` to apply changes you've made.`
> ```
> 
> Thanks !

please update to flutter_facebook_auth:^0.3.1

**Comment by jgrandchavin** [comment]
Thanks a lot !
