### ISSUE TITLE
Flutter for Web Support

### ISSUE THREAD

**Issue by vedangdate** [the-meedu-app/flutter-facebook-auth#21]
Considering this package is being recommended by the FlutterFire team in their official docs (https://firebase.flutter.dev/docs/auth/social#facebook), are there any plans for the Flutter's Web Platform in the future?
(Please say Yes :P)
It would be a huge help if there is web support for the "very much needed" FB auth!

**Comment by the-meedu-app** [comment]
> https://firebase.flutter.dev/docs/auth/social#facebook

If you are trying to make web auth with facebook using firebase you don't need support for web in this package, also the flutter documentation to add web support for plugins that needs use javascript libraries is poor. 

When flutter web has more information about plugins for web I will add these feature.

**Comment by darwin-morocho** [comment]
@vedangdate you can check the pre-release version of this plugin with support for web in https://pub.dev/packages/flutter_facebook_auth/versions/2.0.0-web.7
