### ISSUE TITLE
Facebook login always fail with null token

### ISSUE THREAD

**Issue by Linspirit98** [the-meedu-app/flutter-facebook-auth#22]
Hi, I followed the official documents on FlutterFire, which uses this plugin for authentication on google. The Facebook login request page pops up successfully, and then after I click on login, the page closes but returns me token is null and login canceled. I have set up a Facebook developer account and also followed steps on firebase enabling Facebook login. Did anyways have the same problem? Thank you!

<img width="952" alt="Screen Shot 2020-09-29 at 9 55 01 AM" src="https://user-images.githubusercontent.com/51519489/94567806-da12f900-0239-11eb-98bd-d8ef3f7e2696.png">

<img width="948" alt="Screen Shot 2020-09-29 at 10 10 30 AM" src="https://user-images.githubusercontent.com/51519489/94569702-03348900-023c-11eb-9171-4786935c3378.png">

**Comment by the-meedu-app** [comment]
> Hi, I followed the official documents on FlutterFire, which uses this plugin for authentication on google. The Facebook login request page pops up successfully, and then after I click on login, the page closes but returns me token is null and login canceled. I have set up a Facebook developer account and also followed steps on firebase enabling Facebook login. Did anyways have the same problem? Thank you!
> 
> <img alt="Screen Shot 2020-09-29 at 9 55 01 AM" width="952" src="https://user-images.githubusercontent.com/51519489/94567806-da12f900-0239-11eb-98bd-d8ef3f7e2696.png">
> 
> <img alt="Screen Shot 2020-09-29 at 10 10 30 AM" width="948" src="https://user-images.githubusercontent.com/51519489/94569702-03348900-023c-11eb-9171-4786935c3378.png">

The FlutterFire documentation is not complete you need use the last version of this plugin `0.3.2` and follow the oficial documentation https://github.com/the-meedu-app/flutter-facebook-auth to configure the plugin on iOS and Android

**Comment by Linspirit98** [comment]
Hi, I tried following the official documentation on github and configured the plugin on iOS. However, it always returns me login canceled. Do you know any possible reason for this? Thanks!

<img width="918" alt="Screen Shot 2020-09-29 at 8 53 44 PM" src="https://user-images.githubusercontent.com/51519489/94631313-15dbac00-0296-11eb-9d52-63cedd34c4c3.png">

**Comment by the-meedu-app** [comment]
> Hi, I tried following the official documentation on github and configured the plugin on iOS. However, it always returns me login canceled. Do you know any possible reason for this? Thanks!
> 
> <img alt="Screen Shot 2020-09-29 at 8 53 44 PM" width="918" src="https://user-images.githubusercontent.com/51519489/94631313-15dbac00-0296-11eb-9d52-63cedd34c4c3.png">

I recommend clone the example and change the configuration with your ios and android credentials and run the example to check if the problem persists. I think that is a bad configuration

**Comment by the-meedu-app** [comment]
> > Hi, I tried following the official documentation on github and configured the plugin on iOS. However, it always returns me login canceled. Do you know any possible reason for this? Thanks!
> > <img alt="Screen Shot 2020-09-29 at 8 53 44 PM" width="918" src="https://user-images.githubusercontent.com/51519489/94631313-15dbac00-0296-11eb-9d52-63cedd34c4c3.png">
> 
> I recommend clone the example and change the configuration with your ios and android credentials and run the example to check if the problem persists. I think that is a bad configuration

I been added `flutter-facebook-auth` to my personal project without any problem. Please check the example project

**Comment by Linspirit98** [comment]
Thank you. I solved the problem. I had this one extra line in pod which shouldn't be there.

**Comment by beginner-lang** [comment]
What did you do, please? What code has been added? I was driven mad by the question. grateful

**Comment by Linspirit98** [comment]
> What did you do, please? What code has been added? I was driven mad by the question. grateful

I didn't add any code. I followed the procedure. The only thing i did wrong was I followed the firebase website tutorial and added `pod 'Firebase/Auth'` to my podfile. Also remember to put fb developer project on live.
