### ISSUE TITLE
Couldn't build on iOS

### ISSUE THREAD

**Issue by raffa-12** [the-meedu-app/flutter-facebook-auth#23]
HI, I followed the guideline on Facebook develop website and yours for setting iOS, but i'm having this issue regarding the `Include of non-modular header inside framework module 'FBSDKLoginKit.FBSDKCoreKitImport` even if I set YES. 
I also tried to delete the DerivedData folder, Runner.xcworkspace, Podfile.lock, flutter clean, update the pod, but still no succeed.
FBSDKLoginKit version is 7.1.1, the flutter-facebook-auth version is 0.3.2 and the min version is 10 because i have some other plugins who require it.
Do you have any suggestion on how to fix it?

<img width="808" alt="Screenshot 2020-10-08 at 11 47 25" src="https://user-images.githubusercontent.com/70573968/95443103-78027400-095c-11eb-9949-c13e5e5750a6.png">
<img width="276" alt="Screenshot 2020-10-08 at 11 46 48" src="https://user-images.githubusercontent.com/70573968/95443110-7afd6480-095c-11eb-8b61-996551e86c83.png">

**Comment by the-meedu-app** [comment]
> HI, I followed the guideline on Facebook develop website and yours for setting iOS, but i'm having this issue regarding the `Include of non-modular header inside framework module 'FBSDKLoginKit.FBSDKCoreKitImport` even if I set YES.
> I also tried to delete the DerivedData folder, Runner.xcworkspace, Podfile.lock, flutter clean, update the pod, but still no succeed.
> FBSDKLoginKit version is 7.1.1, the flutter-facebook-auth version is 0.3.2 and the min version is 10 because i have some other plugins who require it.
> Do you have any suggestion on how to fix it?
> 
> <img alt="Screenshot 2020-10-08 at 11 47 25" width="808" src="https://user-images.githubusercontent.com/70573968/95443103-78027400-095c-11eb-9949-c13e5e5750a6.png">
> 
> <img alt="Screenshot 2020-10-08 at 11 46 48" width="276" src="https://user-images.githubusercontent.com/70573968/95443110-7afd6480-095c-11eb-8b61-996551e86c83.png">

Please provide more information like if your project has swift support enabled

**Comment by raffa-12** [comment]
Hi, 
yes it supports swift.

**Comment by the-meedu-app** [comment]
> Hi,
> yes it supports swift.

I'am not sure but could be a problem with your cocoapods version, try to upgrade it and also check that you don't have a wrong configuration in your Podfile

**Comment by raffa-12** [comment]
This is my Podfile and my cocoapods version is 1.9.3.

<img width="500" alt="Screenshot 2020-10-12 at 13 22 40" src="https://user-images.githubusercontent.com/70573968/95741208-26285980-0c8e-11eb-9a2e-5c5beb77c173.png">

**Comment by the-meedu-app** [comment]
> This is my Podfile and my cocoapods version is 1.9.3.
> 
> <img alt="Screenshot 2020-10-12 at 13 22 40" width="500" src="https://user-images.githubusercontent.com/70573968/95741208-26285980-0c8e-11eb-9a2e-5c5beb77c173.png">

I think the problem could be your Podfile. Because you have two unnecesary  dependecies Firebase and Firebase messaging you don't need those dependencies because firebase_core and firebase_messaging already have each one

**Comment by the-meedu-app** [comment]
Closed by inactivity
