### ISSUE TITLE
Login with a different facebook accounts on the same device

### ISSUE THREAD

**Issue by raffa-12** [the-meedu-app/flutter-facebook-auth#25]
Hi, I'm trying to log out and log in with two different facebook accounts, but it always remembers the first one. Can you tell me how can i do it? 
Thank you

**Comment by the-meedu-app** [comment]
Hello that is a default behavior of Facebook app. The Facebook sdk use the default active account. To use other account the user needs sign out and sing in to the new account in the Facebook app or web app
