### ISSUE TITLE
 Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference,

### ISSUE THREAD

**Issue by anoopeashok** [the-meedu-app/flutter-facebook-auth#26]
When i tried facebook login i got this error.

Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference
E/flutter ( 3779):      at ec.dina.flutter_facebook_auth.FlutterFacebookAuthPlugin.onMethodCall(FlutterFacebookAuthPlugin.java:71)
E/flutter ( 3779):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 3779):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 3779):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter ( 3779):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 3779):      at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 3779):      at android.os.Looper.loop(Looper.java:182)
E/flutter ( 3779):      at android.app.ActivityThread.main(ActivityThread.java:7820)
E/flutter ( 3779):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3779):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 3779):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/flutter ( 3779): )
E/flutter ( 3779): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 3779): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 3779): <asynchronous suspension>
E/flutter ( 3779): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 3779): #3      FacebookAuth.login (package:flutter_facebook_auth/flutter_facebook_auth.dart:32:24)
E/flutter ( 3779): #4      FirebaseService.signInWithFacebook (package:mvb/services/firebase_service.dart:43:60)
E/flutter ( 3779): #5      _MainPage.build.<anonymous closure>.<anonymous closure> (package:mvb/screens/home.dart:936:52)
E/flutter ( 3779): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 3779): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 3779): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 3779): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 3779): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 3779): #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter ( 3779): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter ( 3779): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter ( 3779): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 3779): #15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 3779): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 3779): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 3779): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 3779): #19     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 3779): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 3779): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 3779): #22     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 3779): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by the-meedu-app** [comment]
> When i tried facebook login i got this error.
> 
> Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference
> E/flutter ( 3779): at ec.dina.flutter_facebook_auth.FlutterFacebookAuthPlugin.onMethodCall(FlutterFacebookAuthPlugin.java:71)
> E/flutter ( 3779): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> E/flutter ( 3779): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/flutter ( 3779): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
> E/flutter ( 3779): at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter ( 3779): at android.os.MessageQueue.next(MessageQueue.java:336)
> E/flutter ( 3779): at android.os.Looper.loop(Looper.java:182)
> E/flutter ( 3779): at android.app.ActivityThread.main(ActivityThread.java:7820)
> E/flutter ( 3779): at java.lang.reflect.Method.invoke(Native Method)
> E/flutter ( 3779): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> E/flutter ( 3779): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
> E/flutter ( 3779): )
> E/flutter ( 3779): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
> E/flutter ( 3779): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
> E/flutter ( 3779):
> E/flutter ( 3779): #2 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
> E/flutter ( 3779): #3 FacebookAuth.login (package:flutter_facebook_auth/flutter_facebook_auth.dart:32:24)
> E/flutter ( 3779): #4 FirebaseService.signInWithFacebook (package:mvb/services/firebase_service.dart:43:60)
> E/flutter ( 3779): #5 _MainPage.build.. (package:mvb/screens/home.dart:936:52)
> E/flutter ( 3779): #6 _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
> E/flutter ( 3779): #7 _InkResponseState.build. (package:flutter/src/material/ink_well.dart:1111:38)
> E/flutter ( 3779): #8 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
> E/flutter ( 3779): #9 TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
> E/flutter ( 3779): #10 BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
> E/flutter ( 3779): #11 BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
> E/flutter ( 3779): #12 GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
> E/flutter ( 3779): #13 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
> E/flutter ( 3779): #14 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
> E/flutter ( 3779): #15 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
> E/flutter ( 3779): #16 GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
> E/flutter ( 3779): #17 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
> E/flutter ( 3779): #18 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
> E/flutter ( 3779): #19 _rootRunUnary (dart:async/zone.dart:1206:13)
> E/flutter ( 3779): #20 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> E/flutter ( 3779): #21 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
> E/flutter ( 3779): #22 _invoke1 (dart:ui/hooks.dart:265:10)
> E/flutter ( 3779): #23 _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

Have you did configured the plugin on Android?
https://pub.dev/packages/flutter_facebook_auth#install-on-android

If you don't configure the plugin, you will get an error when you try to run the app

**Comment by the-meedu-app** [comment]
Also please add you code to try to reproduce the error, pubspec.yaml, your Flutter SDK version and the flutter_facebook_auth version.

**Comment by rknell** [comment]
I had issues with it throwing the typical "the channel doesn't exist" error and also killing other plugins.

Somehow I had missed the Android setup altogether, fixed that fixed everything else.

Thanks!

**Comment by anoopeashok** [comment]
Sorry for late reply

**flutter doctor**


[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

• No issues found!

**plugin version**

flutter_facebook_auth: "^0.3.2"

**code** (coped from [](https://firebase.flutter.dev/docs/auth/social/) )

  Future<UserCredential> signInWithFacebook() async {
    final LoginResult result = await FacebookAuth.instance.login();

    final FacebookAuthCredential facebookAuthCredential =
        FacebookAuthProvider.credential(result.accessToken.token);

    return await FirebaseAuth.instance
        .signInWithCredential(facebookAuthCredential);
  }

**Comment by the-meedu-app** [comment]
> Sorry for late reply
> 
> **flutter doctor**
> 
> [√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> [√] Android Studio (version 4.0)
> [√] VS Code (version 1.50.1)
> [√] Connected device (1 available)
> 
> • No issues found!
> 
> **plugin version**
> 
> flutter_facebook_auth: "^0.3.2"
> 
> **code** (coped from [flutter firebase login ](https://firebase.flutter.dev/docs/auth/social/) )
> 
> Future signInWithFacebook() async {
> final LoginResult result = await FacebookAuth.instance.login();
> 
> ```
>  final FacebookAuthCredential facebookAuthCredential =
>     FacebookAuthProvider.credential(result.accessToken.token);
> 
>  return await FirebaseAuth.instance
>     .signInWithCredential(facebookAuthCredential);
> ```
> 
> }

Please read the documenation. You need a previous configuration on iOS and Android to use this plugin. You can't just cooy the firebase example code
