### ISSUE TITLE
How to catch exceptions and show it to the user?

### ISSUE THREAD

**Issue by giorgio79** [the-meedu-app/flutter-facebook-auth#27]
One of the most common FB login issues is this:
`" [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: [firebase_auth/account-exists-with-different-credential] An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address."`
https://stackoverflow.com/questions/37947944/authentication-using-facebook-at-first-and-then-google-causes-an-error-in-fireba

**Comment by the-meedu-app** [comment]
> One of the most common FB login issues is this:
> `" [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: [firebase_auth/account-exists-with-different-credential] An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address."`
> https://stackoverflow.com/questions/37947944/authentication-using-facebook-at-first-and-then-google-causes-an-error-in-fireba

This is not an issue of this library because you are trying to handle error of firebase_auth library
