### ISSUE TITLE
Error message return from IOS sdk is incorrect

### ISSUE THREAD

**Issue by RaashVision** [the-meedu-app/flutter-facebook-auth#30]
Hi, first of all thanks a lot for this wonderful library. I have encountered a problem when switching fb account in IOS. I keep getting error **"error make sure that your Info.plist is configured"** . After a lot of debugging, I find it out that the error happens because I didn't logout **(await FacebookAuth.instance.logOut())** from account 1 and try to login to account 2. But in IOS it returning wrong error( **"error make sure that your Info.plist is configured"** ) which is not related to the actual error. I checked the ios code, as the image below, it return the same error message for all the errors. 
![image](https://user-images.githubusercontent.com/14199227/98114363-1f34e580-1ee0-11eb-9b68-78bc89489fbc.png)
Is it something to be fix bro?Or I'm wrong

**Comment by the-meedu-app** [comment]
> Hi, first of all thanks a lot for this wonderful library. I have encountered a problem when switching fb account in IOS. I keep getting error **"error make sure that your Info.plist is configured"** . After a lot of debugging, I find it out that the error happens because I didn't logout **(await FacebookAuth.instance.logOut())** from account 1 and try to login to account 2. But in IOS it returning wrong error( **"error make sure that your Info.plist is configured"** ) which is not related to the actual error. I checked the ios code, as the image below, it return the same error message for all the errors.
> ![image](https://user-images.githubusercontent.com/14199227/98114363-1f34e580-1ee0-11eb-9b68-78bc89489fbc.png)
> Is it something to be fix bro?Or I'm wrong

thanks for your feedback I'll check it to chage the message

**Comment by the-meedu-app** [comment]
> > Hi, first of all thanks a lot for this wonderful library. I have encountered a problem when switching fb account in IOS. I keep getting error **"error make sure that your Info.plist is configured"** . After a lot of debugging, I find it out that the error happens because I didn't logout **(await FacebookAuth.instance.logOut())** from account 1 and try to login to account 2. But in IOS it returning wrong error( **"error make sure that your Info.plist is configured"** ) which is not related to the actual error. I checked the ios code, as the image below, it return the same error message for all the errors.
> > ![image](https://user-images.githubusercontent.com/14199227/98114363-1f34e580-1ee0-11eb-9b68-78bc89489fbc.png)
> > Is it something to be fix bro?Or I'm wrong
> 
> thanks for your feedback I'll check it to change the message

Please check the new version of this library

**Comment by the-meedu-app** [comment]
closed by inactivity
