### ISSUE TITLE
Android fatal crash on physical and emulator devices

### ISSUE THREAD

**Issue by lukasloh** [the-meedu-app/flutter-facebook-auth#31]
Getting a fatal crash on only Android devices when calling `login` on all API levels. iOS is working correctly with the same implementation.

Version: `flutter_facebook_auth: ^0.3.3`

Stack-trace:
```
D/AndroidRuntime(16247): Shutting down VM
E/AndroidRuntime(16247): FATAL EXCEPTION: main
E/AndroidRuntime(16247): Process: com.XXX.XXX, PID: 16247
E/AndroidRuntime(16247): java.lang.NoSuchMethodError: No static method createProxyAuthIntent(Landroid/content/Context;Ljava/lang/String;Ljava/util/Collection;Ljava/lang/String;ZZLcom/facebook/login/DefaultAudience;Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent; in class Lcom/facebook/internal/NativeProtocol; or its super classes (declaration of 'com.facebook.internal.NativeProtocol' appears in /data/app/~~XXX-A==/com.XXX.XXX-XXX==/base.apk!classes2.dex)
E/AndroidRuntime(16247): 	at com.facebook.login.KatanaProxyLoginMethodHandler.tryAuthorize(KatanaProxyLoginMethodHandler.java:44)
E/AndroidRuntime(16247): 	at com.facebook.login.LoginClient.tryCurrentHandler(LoginClient.java:264)
E/AndroidRuntime(16247): 	at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:216)
E/AndroidRuntime(16247): 	at com.facebook.login.LoginClient.authorize(LoginClient.java:121)
E/AndroidRuntime(16247): 	at com.facebook.login.LoginClient.startOrContinueAuth(LoginClient.java:102)
E/AndroidRuntime(16247): 	at com.facebook.login.LoginFragment.onResume(LoginFragment.java:160)
E/AndroidRuntime(16247): 	at androidx.fragment.app.Fragment.performResume(Fragment.java:2748)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1211)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2601)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
E/AndroidRuntime(16247): 	at android.app.Activity.performResume(Activity.java:8160)
E/AndroidRuntime(16247): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
E/AndroidRuntime(16247): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
E/AndroidRuntime(16247): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
E/AndroidRuntime(16247): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(16247): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(16247): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(16247): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16247): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(16247): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(16247): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16247): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(16247): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (16247): Sending signal. PID: 16247 SIG: 9
Lost connection to device.
```

`Flutter  doctor -v` output: 
```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.3 at /Users/XXX/Developer/flutter
    • Framework revision 8874f21e79 (7 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Pixel 3a (mobile) • 94TAY0SSBG • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.
```

Thanks for your help!

**Comment by the-meedu-app** [comment]
> Getting a fatal crash on only Android devices when calling `login` on all API levels. iOS is working correctly with the same implementation.
> 
> Version: `flutter_facebook_auth: ^0.3.3`
> 
> Stack-trace:
> 
> ```
> D/AndroidRuntime(16247): Shutting down VM
> E/AndroidRuntime(16247): FATAL EXCEPTION: main
> E/AndroidRuntime(16247): Process: com.XXX.XXX, PID: 16247
> E/AndroidRuntime(16247): java.lang.NoSuchMethodError: No static method createProxyAuthIntent(Landroid/content/Context;Ljava/lang/String;Ljava/util/Collection;Ljava/lang/String;ZZLcom/facebook/login/DefaultAudience;Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent; in class Lcom/facebook/internal/NativeProtocol; or its super classes (declaration of 'com.facebook.internal.NativeProtocol' appears in /data/app/~~XXX-A==/com.XXX.XXX-XXX==/base.apk!classes2.dex)
> E/AndroidRuntime(16247): 	at com.facebook.login.KatanaProxyLoginMethodHandler.tryAuthorize(KatanaProxyLoginMethodHandler.java:44)
> E/AndroidRuntime(16247): 	at com.facebook.login.LoginClient.tryCurrentHandler(LoginClient.java:264)
> E/AndroidRuntime(16247): 	at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:216)
> E/AndroidRuntime(16247): 	at com.facebook.login.LoginClient.authorize(LoginClient.java:121)
> E/AndroidRuntime(16247): 	at com.facebook.login.LoginClient.startOrContinueAuth(LoginClient.java:102)
> E/AndroidRuntime(16247): 	at com.facebook.login.LoginFragment.onResume(LoginFragment.java:160)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.Fragment.performResume(Fragment.java:2748)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1211)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2601)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
> E/AndroidRuntime(16247): 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
> E/AndroidRuntime(16247): 	at android.app.Activity.performResume(Activity.java:8160)
> E/AndroidRuntime(16247): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
> E/AndroidRuntime(16247): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
> E/AndroidRuntime(16247): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
> E/AndroidRuntime(16247): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
> E/AndroidRuntime(16247): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
> E/AndroidRuntime(16247): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
> E/AndroidRuntime(16247): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(16247): 	at android.os.Looper.loop(Looper.java:223)
> E/AndroidRuntime(16247): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
> E/AndroidRuntime(16247): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(16247): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> E/AndroidRuntime(16247): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> I/Process (16247): Sending signal. PID: 16247 SIG: 9
> Lost connection to device.
> ```
> 
> `Flutter doctor -v` output:
> 
> ```
> [✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-US)
>     • Flutter version 1.22.3 at /Users/XXX/Developer/flutter
>     • Framework revision 8874f21e79 (7 days ago), 2020-10-29 14:14:35 -0700
>     • Engine revision a1440ca392
>     • Dart version 2.10.3
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/XXX/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.1, Build version 12A7403
>     • CocoaPods version 1.10.0
> 
> [!] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.50.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.16.0
> 
> [✓] Connected device (1 available)
>     • Pixel 3a (mobile) • 94TAY0SSBG • android-arm64 • Android 11 (API 30)
> 
> ! Doctor found issues in 1 category.
> ```
> 
> Thanks for your help!

Are you sure that you have been configured the plugin on Android before use it? Please add your android configuration

**Comment by lukasloh** [comment]
@the-meedu-app I think it is correctly configured. I copied the facebook manifest configuration that is linked inside of the readme.

`strings.xml`
```
<resources>
    <string name="facebook_app_id">XXX</string>
    <string name="fb_login_protocol_scheme">fbXXX</string>

    <string name="app_name">XXX</string>
</resources>
```

`AndroidManifest.xml`
```
...

        <meta-data android:name="com.facebook.sdk.ApplicationId" 
        android:value="@string/facebook_app_id"/>
    
        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                    "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity
        android:name="com.facebook.CustomTabActivity"
        android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

...

</application>

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

</manifest>
```

**Comment by the-meedu-app** [comment]
> @the-meedu-app I think it is correctly configured. I copied the facebook manifest configuration that is linked inside of the readme. Thanks!
> 
> `strings.xml`
> 
> ```
> <resources>
>     <string name="facebook_app_id">XXX</string>
>     <string name="fb_login_protocol_scheme">fbXXX</string>
> 
>     <string name="app_name">XXX</string>
> </resources>
> ```
> 
> `AndroidManifest.xml`
> 
> ```
> ...
> 
>         <meta-data android:name="com.facebook.sdk.ApplicationId" 
>         android:value="@string/facebook_app_id"/>
>     
>         <activity android:name="com.facebook.FacebookActivity"
>             android:configChanges=
>                     "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
>             android:label="@string/app_name" />
>         <activity
>         android:name="com.facebook.CustomTabActivity"
>         android:exported="true">
>             <intent-filter>
>                 <action android:name="android.intent.action.VIEW" />
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
>                 <data android:scheme="@string/fb_login_protocol_scheme" />
>             </intent-filter>
>         </activity>
> 
> ...
> 
> </application>
> 
>     <uses-permission android:name="android.permission.INTERNET"/>
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
> 
> </manifest>
> ```

Please add the complete AndroidManifesr also please check the example project configuration

**Comment by lukasloh** [comment]
@the-meedu-app `AndroidManifest.xml`:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.XXX_flutter">
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:allowBackup="false"
        android:fullBackupContent="false"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:label="XXX">
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleInstance"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:scheme="https"
                    android:host="XXX.com"
                    android:pathPrefix="/XXX" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:scheme="XXX"
                    android:host="XX.XX" />
                <data
                    android:scheme="XX"
                    android:host="XX.XX" />
            </intent-filter>
        </activity>
        <meta-data android:name="com.facebook.sdk.ApplicationId" 
        android:value="@string/facebook_app_id"/>
                <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                    "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity
        android:name="com.facebook.CustomTabActivity"
        android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <provider
                android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
                android:authorities="${applicationId}.flutter_downloader.provider"
                android:exported="false"
                android:grantUriPermissions="true">
                <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/provider_paths"/>
        </provider>
    </application>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
</manifest>
```

**Comment by the-meedu-app** [comment]
> @the-meedu-app `AndroidManifest.xml`:
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.example.XXX_flutter">
>     <application
>         android:name="io.flutter.app.FlutterApplication"
>         android:allowBackup="false"
>         android:fullBackupContent="false"
>         android:icon="@mipmap/ic_launcher"
>         android:roundIcon="@mipmap/ic_launcher_round"
>         android:label="XXX">
>         <activity
>             android:name=".MainActivity"
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>             android:hardwareAccelerated="true"
>             android:launchMode="singleInstance"
>             android:theme="@style/LaunchTheme"
>             android:windowSoftInputMode="adjustResize">
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN" />
>                 <category android:name="android.intent.category.LAUNCHER" />
>             </intent-filter>
>             <intent-filter android:autoVerify="true">
>                 <action android:name="android.intent.action.VIEW" />
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
>                 <data
>                     android:scheme="https"
>                     android:host="XXX.com"
>                     android:pathPrefix="/XXX" />
>             </intent-filter>
>             <intent-filter>
>                 <action android:name="android.intent.action.VIEW" />
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
>                 <data
>                     android:scheme="XXX"
>                     android:host="XX.XX" />
>                 <data
>                     android:scheme="XX"
>                     android:host="XX.XX" />
>             </intent-filter>
>         </activity>
>         <meta-data android:name="com.facebook.sdk.ApplicationId" 
>         android:value="@string/facebook_app_id"/>
>                 <activity android:name="com.facebook.FacebookActivity"
>             android:configChanges=
>                     "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
>             android:label="@string/app_name" />
>         <activity
>         android:name="com.facebook.CustomTabActivity"
>         android:exported="true">
>             <intent-filter>
>                 <action android:name="android.intent.action.VIEW" />
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
>                 <data android:scheme="@string/fb_login_protocol_scheme" />
>             </intent-filter>
>         </activity>
>         <meta-data
>             android:name="flutterEmbedding"
>             android:value="2" />
>         <provider
>                 android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
>                 android:authorities="${applicationId}.flutter_downloader.provider"
>                 android:exported="false"
>                 android:grantUriPermissions="true">
>                 <meta-data
>                     android:name="android.support.FILE_PROVIDER_PATHS"
>                     android:resource="@xml/provider_paths"/>
>         </provider>
>     </application>
>     <uses-permission android:name="android.permission.INTERNET"/>
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
> </manifest>
> ```

Your configuration looks right, may we have a conflict with other library. Try the new version of flutter_facebook_auht

**Comment by the-meedu-app** [comment]
closed by inactivity

**Comment by lukasloh** [comment]
@the-meedu-app sorry for the lack of response, the new version works great! Thanks!
