### ISSUE TITLE
Facebook login never ends on iOS

### ISSUE THREAD

**Issue by jezsung** [the-meedu-app/flutter-facebook-auth#32]
```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H15, locale en-KR)
    • Flutter version 1.22.3 at /usr/local/Caskroom/flutter/1.22.3/flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jaesunghong/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • **** iPhone (mobile) • **** • ios
      • iOS 13.5.1
```

After calling `FacebookAuth.instance.login()`, the web view pop up and Facebook sends me to the Facebook app. And then after I clicked the Continue as USERNAME button it sends me back to my app but the web view still persists and doesn't end the login process. Whenever I click on the Cancel button on the top left corner, it just throws FacebookAuthException with `errorCode == 'CANCELLED'`. I did check all the settings for iOS on my app and Facebook console.

**Comment by jezsung** [comment]
Podfile
```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.33.0'
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

info.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>$(APP_DISPLAY_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>dropshipit</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>

	<key>CFBundleURLTypes</key>
    <array>
    	<dict>
    		<key>CFBundleTypeRole</key>
    		<string>Editor</string>
    		<key>CFBundleURLSchemes</key>
    		<array>
    		    <string>fb2572304256420570</string>
    			<string>com.googleusercontent.apps.268608212248-8csngu9qb096k8rpa1idk06uo9frr5qj</string>
    		</array>
    	</dict>
    </array>

    <key>FacebookAppID</key>
    <string>2572304256420570</string>
    <key>FacebookDisplayName</key>
    <string>Dropship Up</string>
    <key>LSApplicationQueriesSchemes</key>
    <array>
      <string>fbapi</string>
      <string>fb-messenger-share-api</string>
      <string>fbauth2</string>
      <string>fbshareextension</string>
    </array>
</dict>
</plist>

```

**Comment by the-meedu-app** [comment]
> Podfile
> 
> ```
> # Uncomment this line to define a global platform for your project
> platform :ios, '9.0'
> 
> # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
> ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> 
> project 'Runner', {
>   'Debug' => :debug,
>   'Profile' => :release,
>   'Release' => :release,
> }
> 
> def flutter_root
>   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
>   unless File.exist?(generated_xcode_build_settings_path)
>     raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
>   end
> 
>   File.foreach(generated_xcode_build_settings_path) do |line|
>     matches = line.match(/FLUTTER_ROOT\=(.*)/)
>     return matches[1].strip if matches
>   end
>   raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
> end
> 
> require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
> 
> flutter_ios_podfile_setup
> 
> target 'Runner' do
>   pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.33.0'
>   use_frameworks!
>   use_modular_headers!
> 
>   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>   end
> end
> ```
> 
> info.plist
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>CFBundleDevelopmentRegion</key>
> 	<string>$(DEVELOPMENT_LANGUAGE)</string>
> 	<key>CFBundleDisplayName</key>
> 	<string>$(APP_DISPLAY_NAME)</string>
> 	<key>CFBundleExecutable</key>
> 	<string>$(EXECUTABLE_NAME)</string>
> 	<key>CFBundleIdentifier</key>
> 	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
> 	<key>CFBundleInfoDictionaryVersion</key>
> 	<string>6.0</string>
> 	<key>CFBundleName</key>
> 	<string>dropshipit</string>
> 	<key>CFBundlePackageType</key>
> 	<string>APPL</string>
> 	<key>CFBundleShortVersionString</key>
> 	<string>$(FLUTTER_BUILD_NAME)</string>
> 	<key>CFBundleSignature</key>
> 	<string>????</string>
> 	<key>CFBundleVersion</key>
> 	<string>$(FLUTTER_BUILD_NUMBER)</string>
> 	<key>LSRequiresIPhoneOS</key>
> 	<true/>
> 	<key>UILaunchStoryboardName</key>
> 	<string>LaunchScreen</string>
> 	<key>UIMainStoryboardFile</key>
> 	<string>Main</string>
> 	<key>UISupportedInterfaceOrientations</key>
> 	<array>
> 		<string>UIInterfaceOrientationPortrait</string>
> 		<string>UIInterfaceOrientationLandscapeLeft</string>
> 		<string>UIInterfaceOrientationLandscapeRight</string>
> 	</array>
> 	<key>UISupportedInterfaceOrientations~ipad</key>
> 	<array>
> 		<string>UIInterfaceOrientationPortrait</string>
> 		<string>UIInterfaceOrientationPortraitUpsideDown</string>
> 		<string>UIInterfaceOrientationLandscapeLeft</string>
> 		<string>UIInterfaceOrientationLandscapeRight</string>
> 	</array>
> 	<key>UIViewControllerBasedStatusBarAppearance</key>
> 	<false/>
> 
> 	<key>CFBundleURLTypes</key>
>     <array>
>     	<dict>
>     		<key>CFBundleTypeRole</key>
>     		<string>Editor</string>
>     		<key>CFBundleURLSchemes</key>
>     		<array>
>     		        <string>fbMy_APP_ID</string>
>     		</array>
>     	</dict>
>     </array>
> 
>     <key>FacebookAppID</key>
>     <string>My_APP_ID</string>
>     <key>FacebookDisplayName</key>
>     <string>Dropship Up</string>
>     <key>LSApplicationQueriesSchemes</key>
>     <array>
>       <string>fbapi</string>
>       <string>fb-messenger-share-api</string>
>       <string>fbauth2</string>
>       <string>fbshareextension</string>
>     </array>
> </dict>
> </plist>
> ```

Please clone the project and run the example project with your Facebook credentials and let me now if the problem persist. If not maybe you have a wrong configuration, also please add your pubspect.yaml and your code to reproduce the error. I tried with my iPhone x with ios 14.2 and everything is ok

**Comment by jezsung** [comment]
@the-meedu-app Maybe it's iOS version issue? I changed the package version to 0.3.3 and now it works. I didn't change any configuration files so that the bug must be somewhere in the `FacebookAuth.instance.login()` method.

``` yaml
name: dropshipit
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3
  device_preview: ^0.4.8
  equatable: ^1.2.5
  firebase_analytics: ^6.2.0
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  flutter_bloc: ^6.1.0
  flutter_facebook_auth: ^0.3.3
  flutter_signin_button: ^1.1.0
  fluttertoast: ^7.1.1
  google_sign_in: ^4.5.6
  line_icons: ^0.2.0
  rxdart: ^0.24.1
  sign_in_with_apple: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  faker: ^1.2.1
  mockito: ^4.1.3
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
```

This is my yaml file and keep in mind that when I tried it on version 1.0.0+4 it failed but on 0.3.3 it works.

**Comment by the-meedu-app** [comment]
> @the-meedu-app Maybe it's iOS version issue? I changed the package version to 0.3.3 and now it works. I didn't change any configuration files so that the bug must be somewhere in the `FacebookAuth.instance.login()` method.
> 
> ```yaml
> name: dropshipit
> description: A new Flutter application.
> publish_to: 'none'
> version: 1.0.0+1
> 
> environment:
>   sdk: ">=2.7.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   cloud_firestore: ^0.14.3
>   device_preview: ^0.4.8
>   equatable: ^1.2.5
>   firebase_analytics: ^6.2.0
>   firebase_auth: ^0.18.3
>   firebase_core: ^0.5.2
>   flutter_bloc: ^6.1.0
>   flutter_facebook_auth: ^0.3.3
>   flutter_signin_button: ^1.1.0
>   fluttertoast: ^7.1.1
>   google_sign_in: ^4.5.6
>   line_icons: ^0.2.0
>   rxdart: ^0.24.1
>   sign_in_with_apple: ^2.5.4
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
>   bloc_test: ^7.1.0
>   faker: ^1.2.1
>   mockito: ^4.1.3
>   pedantic: ^1.9.0
> 
> flutter:
>   uses-material-design: true
> ```
> 
> This is my yaml file and keep in mind that when I tried it on version 1.0.0+4 it failed but on 0.3.3 it works.

I think the problem could be because you are using other auth providers like google. I will try to reproduce it

**Comment by the-meedu-app** [comment]
> > @the-meedu-app Maybe it's iOS version issue? I changed the package version to 0.3.3 and now it works. I didn't change any configuration files so that the bug must be somewhere in the `FacebookAuth.instance.login()` method.
> > ```yaml
> > name: dropshipit
> > description: A new Flutter application.
> > publish_to: 'none'
> > version: 1.0.0+1
> > 
> > environment:
> >   sdk: ">=2.7.0 <3.0.0"
> > 
> > dependencies:
> >   flutter:
> >     sdk: flutter
> >   cloud_firestore: ^0.14.3
> >   device_preview: ^0.4.8
> >   equatable: ^1.2.5
> >   firebase_analytics: ^6.2.0
> >   firebase_auth: ^0.18.3
> >   firebase_core: ^0.5.2
> >   flutter_bloc: ^6.1.0
> >   flutter_facebook_auth: ^0.3.3
> >   flutter_signin_button: ^1.1.0
> >   fluttertoast: ^7.1.1
> >   google_sign_in: ^4.5.6
> >   line_icons: ^0.2.0
> >   rxdart: ^0.24.1
> >   sign_in_with_apple: ^2.5.4
> > 
> > dev_dependencies:
> >   flutter_test:
> >     sdk: flutter
> >   bloc_test: ^7.1.0
> >   faker: ^1.2.1
> >   mockito: ^4.1.3
> >   pedantic: ^1.9.0
> > 
> > flutter:
> >   uses-material-design: true
> > ```
> > 
> > 
> > This is my yaml file and keep in mind that when I tried it on version 1.0.0+4 it failed but on 0.3.3 it works.
> 
> I think the problem could be because you are using other auth providers like google. I will try to reproduce it

@jezsung  I've tried to reproduce the issue but I couldn't. I think you are not providing the enough information to reproduce the issue. 

Here you have my configuration 

flutter doctor -v
```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    es-419)
    • Flutter version 1.22.4 at /Users/darwin/development/flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/darwin/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/darwin/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone de Darwin (mobile) • b365d4a56ada2a7ed316e77fccf1f4a45ee8a454 • ios
      • iOS 14.2
    ! Error: iPhone de Darwin is busy: Copying cache files from device. Xcode
      will continue when iPhone de Darwin is finished. (code -10)

• No issues found!
```


info.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Flutter FAuth Example</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>facebook_auth_example</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb{fb-app-id}</string>
                <string>com.googleusercontent.apps.{CLIENT_ID}</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FacebookAppID</key>
	<string>{fb-app-id}</string>
	<key>FacebookDisplayName</key>
	<string>Flutter FAuth Example</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
        <string>fbapi</string>
        <string>fb-messenger-share-api</string>
        <string>fbauth2</string>
        <string>fbshareextension</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```


pubspec.yaml
```yaml
name: facebook_auth_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_facebook_auth: ^1.0.0+3
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6
  flutter_signin_button: ^1.1.0
  sign_in_with_apple: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```



dart code
```dart
import 'dart:convert';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

String prettyPrint(Map json) {
  JsonEncoder encoder = new JsonEncoder.withIndent('  ');
  String pretty = encoder.convert(json);
  return pretty;
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  HomePage({Key key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _fetching = true;

  AccessToken _accessToken;
  Map<String, dynamic> _userData;

  @override
  void initState() {
    super.initState();
    _checkLogin();
  }

  Future<void> _checkLogin() async {
    await Future.delayed(Duration(seconds: 1));
    _accessToken = await FacebookAuth.instance.isLogged;
    if (_accessToken != null) {
      await _getUserData();
    }

    _fetching = false;
    setState(() {});
  }

  Future<void> _getUserData() async {
    _userData = await FacebookAuth.instance.getUserData(fields: "email,name,picture.width(300),birthday,friends");
  }

  Future<void> _loginWithFacebook() async {
    try {
      setState(() {
        _fetching = true;
      });
      _accessToken = await FacebookAuth.instance.login(
        permissions: [
          'email',
          'public_profile',
          'user_birthday',
          'user_friends',
        ],
      );
      await _getUserData();
      setState(() {
        _fetching = false;
      });
      print(
        _accessToken.toJson(),
      );
    } catch (e, s) {
      setState(() {
        _fetching = false;
      });
      if (e is FacebookAuthException) {
        switch (e.errorCode) {
          case FacebookAuthErrorCode.OPERATION_IN_PROGRESS:
            print("FacebookAuthErrorCode.OPERATION_IN_PROGRESS");
            break;
          case FacebookAuthErrorCode.CANCELLED:
            print("FacebookAuthErrorCode.CANCELLED");
            break;

          case FacebookAuthErrorCode.FAILED:
            print("FacebookAuthErrorCode.FAILED");
            break;
        }
      }
    }
  }

  Future<void> _logOut() async {
    await FacebookAuth.instance.logOut();
    setState(() {
      _accessToken = null;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          width: double.infinity,
          height: double.infinity,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (!_fetching && _accessToken == null)
                FlatButton(
                  onPressed: _loginWithFacebook,
                  color: Colors.blueAccent,
                  child: Text("LOGIN"),
                ),
              if (_fetching) CircularProgressIndicator(),
              if (_accessToken != null) ...[
                Text("HI ...."),
                Text(prettyPrint(_userData)),
                SizedBox(height: 20),
                FlatButton(
                  onPressed: _logOut,
                  color: Colors.blueAccent,
                  child: Text("LOG OUT"),
                ),
              ]
            ],
          ),
        ),
      ),
    );
  }
}
```




Please clone this repo https://github.com/meedu-app/flutter-facebook-login-example/tree/firebase_auth and change with your `GoogleService-Info.plist` and your Facebook credentials and let me know if the problem persists

**Comment by the-meedu-app** [comment]
@jezsung Also could be a problem of the facebook sdk because `flutter_facebook_auth:0.3.3` use the  `facebook sdk ^7.1.0` and `flutter_facebook_auth: 1.0.0+3` uses  `facebook sdk ^8.1.0` so I've updated the  `facebook sdk to 8.2.0` please check if the `flutter_facebook_auth:1.0.1` fix the problem

**Comment by jezsung** [comment]
@the-meedu-app It works after upgrading to 1.1.0. Looks like it was a Facebook SDK issue. Thanks!
